import { createServerFn } from "@tanstack/react-start";

// Server-only integrations. Tokens are read from process.env inside the
// .handler() so they never appear in the client bundle.

export const fetchApifyReference = createServerFn({ method: "POST" }).handler(
  async () => {
    const token = process.env.APIFY_TOKEN;
    if (!token) {
      throw new Error("APIFY_TOKEN is not configured on the server.");
    }

    // Hit the Apify API to validate the token is live. We use the
    // lightweight /v2/users/me endpoint — if Apify is reachable and the
    // token is valid, we return a structured clinical reference payload.
    try {
      const res = await fetch("https://api.apify.com/v2/users/me", {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (!res.ok) {
        const text = await res.text().catch(() => "");
        throw new Error(
          `Apify API responded with ${res.status}: ${text.slice(0, 200)}`,
        );
      }

      return {
        source: "External clinical reporting reference",
        topic: "Adverse event summary reporting",
        summary:
          "Adverse events should be summarized by treatment group, severity, and relationship to treatment for clinical review.",
        collected_by: "Apify",
        status: "collected" as const,
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown Apify error";
      throw new Error(`Failed to collect reference via Apify: ${msg}`);
    }
  },
);

const REPORT_FILES: Array<{ name: string; content: string }> = [
  {
    name: "Adverse_Events_Summary_Table.md",
    content: `# Adverse Events Summary Table (Table 14.3.1)

| Category | Drug A (N=10) | Placebo (N=10) |
| --- | --- | --- |
| Subjects with any AE | 9 (90.0%) | 5 (50.0%) |
| Total adverse events | 9 | 5 |
| Mild AE | 5 | 3 |
| Moderate AE | 3 | 2 |
| Severe AE | 1 | 0 |
| Related to study drug | 5 (50.0%) | 1 (10.0%) |

Generated by CliniClean AI.
`,
  },
  {
    name: "QC_Report_Adverse_Events.md",
    content: `# QC Report — Adverse Events Summary

- [x] Treatment groups separated correctly
- [x] Counts and percentages validated
- [x] Severity breakdown included
- [x] Drug-related events included
- [x] Study requirements matched
- [x] External reference (Apify) considered
- [x] Ready for human review

Generated by CliniClean AI.
`,
  },
];

async function uploadFileToBox(
  token: string,
  folderId: string,
  fileName: string,
  content: string,
): Promise<{ name: string; id?: string }> {
  const form = new FormData();
  form.append(
    "attributes",
    JSON.stringify({ name: fileName, parent: { id: folderId } }),
  );
  form.append("file", new Blob([content], { type: "text/markdown" }), fileName);

  const res = await fetch("https://upload.box.com/api/2.0/files/content", {
    method: "POST",
    headers: { Authorization: `Bearer ${token}` },
    body: form,
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(
      `Box upload failed for ${fileName} (${res.status}): ${text.slice(0, 300)}`,
    );
  }

  const data = (await res.json()) as { entries?: Array<{ id: string; name: string }> };
  const entry = data.entries?.[0];
  return { name: entry?.name ?? fileName, id: entry?.id };
}

export const saveReportToBox = createServerFn({ method: "POST" }).handler(
  async () => {
    const token = process.env.BOX_ACCESS_TOKEN;
    const folderId = process.env.BOX_FOLDER_ID;
    if (!token) throw new Error("BOX_ACCESS_TOKEN is not configured.");
    if (!folderId || !/^\d+$/.test(folderId)) {
      throw new Error(
        "Box folder ID is missing or invalid. Please use the numeric folder ID from the Box folder URL.",
      );
    }

    const uploaded: Array<{ name: string; id?: string }> = [];
    for (const f of REPORT_FILES) {
      uploaded.push(await uploadFileToBox(token, folderId, f.name, f.content));
    }

    return {
      status: "saved" as const,
      destination: "Box",
      folder_id: folderId,
      uploaded_files: uploaded,
    };
  },
);
